# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a008341f114f0f72b5f92669072cf5ae8a90d54d20949969450e0756e821e4ceb449fc1d054f3315c95556a3c6478e56687ae9fa43e6677fef2b1d8683a6b62b

test:
  secret_key_base: 83fcd181452b0e5a62057dfc01870420e3779fda034c1bdd30fea3e73cfbe927cec6dbf8c9f8d6c120d74c8e67ac666dc1d9190e953ea7eb8ea831092a972357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
